# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(911, 894)
        self.gridLayout_8 = QtWidgets.QGridLayout(Form)
        self.gridLayout_8.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.view_saved_links_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_saved_links_btn.sizePolicy().hasHeightForWidth())
        self.view_saved_links_btn.setSizePolicy(sizePolicy)
        self.view_saved_links_btn.setObjectName("view_saved_links_btn")
        self.horizontalLayout.addWidget(self.view_saved_links_btn)
        self.close_chrome_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_chrome_btn.sizePolicy().hasHeightForWidth())
        self.close_chrome_btn.setSizePolicy(sizePolicy)
        self.close_chrome_btn.setObjectName("close_chrome_btn")
        self.horizontalLayout.addWidget(self.close_chrome_btn)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_site_btn = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_site_btn.sizePolicy().hasHeightForWidth())
        self.search_site_btn.setSizePolicy(sizePolicy)
        self.search_site_btn.setObjectName("search_site_btn")
        self.horizontalLayout_2.addWidget(self.search_site_btn)
        self.search_elems_btn = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_elems_btn.sizePolicy().hasHeightForWidth())
        self.search_elems_btn.setSizePolicy(sizePolicy)
        self.search_elems_btn.setObjectName("search_elems_btn")
        self.horizontalLayout_2.addWidget(self.search_elems_btn)
        self.gridLayout_8.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_engine = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_engine.sizePolicy().hasHeightForWidth())
        self.search_engine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search_engine.setFont(font)
        self.search_engine.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search_engine.setObjectName("search_engine")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.search_engine)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.yandex_rbtn = QtWidgets.QRadioButton(self.search_engine)
        self.yandex_rbtn.setChecked(True)
        self.yandex_rbtn.setObjectName("yandex_rbtn")
        self.verticalLayout_2.addWidget(self.yandex_rbtn)
        self.google_rbtn = QtWidgets.QRadioButton(self.search_engine)
        self.google_rbtn.setObjectName("google_rbtn")
        self.verticalLayout_2.addWidget(self.google_rbtn)
        self.mailr_rbtn = QtWidgets.QRadioButton(self.search_engine)
        self.mailr_rbtn.setObjectName("mailr_rbtn")
        self.verticalLayout_2.addWidget(self.mailr_rbtn)
        self.horizontalLayout_3.addWidget(self.search_engine)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.splitter_2 = QtWidgets.QSplitter(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_13 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.phrase_le = QtWidgets.QLineEdit(self.layoutWidget2)
        self.phrase_le.setObjectName("phrase_le")
        self.gridLayout.addWidget(self.phrase_le, 0, 1, 1, 1)
        self.url_site_le = QtWidgets.QLineEdit(self.layoutWidget2)
        self.url_site_le.setObjectName("url_site_le")
        self.gridLayout.addWidget(self.url_site_le, 1, 1, 1, 1)
        self.geolocation_le = QtWidgets.QLineEdit(self.layoutWidget2)
        self.geolocation_le.setObjectName("geolocation_le")
        self.gridLayout.addWidget(self.geolocation_le, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.splitter_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.css_le = QtWidgets.QLineEdit(self.frame_2)
        self.css_le.setObjectName("css_le")
        self.gridLayout_3.addWidget(self.css_le, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.xpaath_le = QtWidgets.QLineEdit(self.frame_2)
        self.xpaath_le.setObjectName("xpaath_le")
        self.gridLayout_3.addWidget(self.xpaath_le, 2, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.number_elems_sb = QtWidgets.QSpinBox(self.frame_2)
        self.number_elems_sb.setMinimum(1)
        self.number_elems_sb.setMaximum(9999)
        self.number_elems_sb.setObjectName("number_elems_sb")
        self.gridLayout_2.addWidget(self.number_elems_sb, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.timer_sb = QtWidgets.QSpinBox(self.frame_2)
        self.timer_sb.setSpecialValueText("")
        self.timer_sb.setMinimum(1)
        self.timer_sb.setMaximum(9999)
        self.timer_sb.setObjectName("timer_sb")
        self.gridLayout_7.addWidget(self.timer_sb, 0, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 3, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 0, 0, 1, 1)
        self.num_pages_prog_bar = QtWidgets.QProgressBar(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.num_pages_prog_bar.setFont(font)
        self.num_pages_prog_bar.setProperty("value", 0)
        self.num_pages_prog_bar.setTextVisible(True)
        self.num_pages_prog_bar.setObjectName("num_pages_prog_bar")
        self.gridLayout_9.addWidget(self.num_pages_prog_bar, 1, 1, 1, 1)
        self.scrolling_prog_bar = QtWidgets.QProgressBar(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scrolling_prog_bar.setFont(font)
        self.scrolling_prog_bar.setAutoFillBackground(False)
        self.scrolling_prog_bar.setProperty("value", 0)
        self.scrolling_prog_bar.setObjectName("scrolling_prog_bar")
        self.gridLayout_9.addWidget(self.scrolling_prog_bar, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_5, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.clearNotepad = QtWidgets.QPushButton(self.frame_4)
        self.clearNotepad.setObjectName("clearNotepad")
        self.horizontalLayout_4.addWidget(self.clearNotepad)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.notepad = QtWidgets.QTextBrowser(self.frame_4)
        self.notepad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notepad.setReadOnly(False)
        self.notepad.setObjectName("notepad")
        self.verticalLayout.addWidget(self.notepad)
        self.gridLayout_8.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.log_text_browser = QtWidgets.QTextBrowser(self.frame_3)
        self.log_text_browser.setObjectName("log_text_browser")
        self.gridLayout_4.addWidget(self.log_text_browser, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_3, 4, 0, 1, 1)

        self.retranslateUi(Form)
        self.clearNotepad.clicked.connect(self.notepad.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SEO Sprint and Profitcenter"))
        self.view_saved_links_btn.setText(_translate("Form", "Адреса посещенных страниц"))
        self.close_chrome_btn.setText(_translate("Form", "Закрыть Google Chrome"))
        self.search_site_btn.setText(_translate("Form", "Найти сайт"))
        self.search_elems_btn.setText(_translate("Form", "Просморт ссылок на активной странице"))
        self.search_engine.setTitle(_translate("Form", "Поисковая система"))
        self.yandex_rbtn.setText(_translate("Form", "Yandex"))
        self.google_rbtn.setText(_translate("Form", "Google"))
        self.mailr_rbtn.setText(_translate("Form", "MailRu"))
        self.label_13.setText(_translate("Form", "Данные для поиска сайта"))
        self.label_2.setText(_translate("Form", "Адрес сайта"))
        self.label.setText(_translate("Form", "Фраза для поиска"))
        self.label_3.setText(_translate("Form", "Местоположение (только для Яндекс)"))
        self.label_8.setText(_translate("Form", "Выбор элементов на активной странице"))
        self.label_4.setText(_translate("Form", "CSS-path элементов"))
        self.label_5.setText(_translate("Form", "XPATH элементов"))
        self.label_6.setText(_translate("Form", "Количество элементов"))
        self.label_7.setText(_translate("Form", "Таймер"))
        self.label_11.setText(_translate("Form", "Прокрутка страницы"))
        self.num_pages_prog_bar.setFormat(_translate("Form", "%v страница"))
        self.scrolling_prog_bar.setFormat(_translate("Form", "%v кликов"))
        self.label_12.setText(_translate("Form", "Количество просмотренных страниц"))
        self.label_10.setText(_translate("Form", "Блокнотик"))
        self.clearNotepad.setText(_translate("Form", "Очистить блокнотик"))
        self.label_9.setText(_translate("Form", "Сообщения скрипта"))


